default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['USERNAME'] %>
  password: <%= ENV['PASSWORD'] %>
  host: <%= ENV['HOST'] %>
  port: <%= ENV['PORT'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  variables:
    statement_timeout: <%= ENV.fetch("DATABASE_TIMEOUT") { 10000 } %>

development:
  <<: *default
  database: <%= "#{ENV['DATABASE']}_development" %>

test:
  <<: *default
  database: <%= "#{ENV['DATABASE']}_test" %>

production:
  <<: *default
  database: <%= ENV['DATABASE'] %>
