source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.4'
gem 'rails', '~> 6.0.0'
gem 'pg', '>= 0.18', '< 2.0'
gem 'puma', '~> 3.12.4'
gem 'bootsnap', '>= 1.1.0', require: false
gem 'rubocop'
gem 'jbuilder', '~> 2.5'
gem 'redis'
gem 'hutch'
gem 'rack-cors'

group :development, :test do
  gem 'faker'
  gem 'rspec-rails'
  gem 'pry-nav'
  gem 'pry-rails'
  gem 'pry-rescue'
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  gem 'json_matchers'
  gem 'rspec-collection_matchers'
  gem 'shoulda-matchers', '~> 3.0'
  gem 'simplecov', require: false
  gem 'factory_bot_rails', '~> 4.8', '>= 4.8.2'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
